- id: doxygen-warnings
  name: Check for doxygen warnings
  description: Runs doxygen against C/C++ headers and source files
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: check-doxygen-warnings.py
